# Data Preparation and Analysis

In [1]:
import pandas as pd

### Dummy data

In [7]:
student_data = {'id' : ['1001-2', '1002-2', '1003-2', '1004-2', '1005-2', '1006-2'],
               'name' : ['Louisa Decker', 'Sioned Allan', 'Cayden Collier', 'Jerome Rudd', 'Jibril Morrow', 'David Strouut'],
                'section' : ['1A', '2A', '3B', '3D', '2C', '1A'],
                'year' : ['BSIT-1', 'BSIT-2', 'BSIT-3', 'BSIT-3', 'BSIT-2', 'BSIT-1']
               }

#### Student Data Frame from 'student_data' dictionary

In [8]:
student_data_frame = pd.DataFrame(student_data)

In [9]:
grades_data = {'id' : ['1001-2', '1002-2', '1003-2', '1004-2', '1005-2', '1006-2'],
              'gpa' : [91., 92., 88., 83., 75., 80.]
              }

#### Grades Data Frame from 'grades_data'

In [10]:
grades_data_frame = pd.DataFrame(grades_data)

#### Merged student and grade Data Frame

In [11]:
student_df = pd.merge(student_data_frame, grades_data_frame, how='inner', on='id')

In [12]:
student_df

       id            name section    year   gpa
0  1001-2   Louisa Decker      1A  BSIT-1  91.0
1  1002-2    Sioned Allan      2A  BSIT-2  92.0
2  1003-2  Cayden Collier      3B  BSIT-3  88.0
3  1004-2     Jerome Rudd      3D  BSIT-3  83.0
4  1005-2   Jibril Morrow      2C  BSIT-2  75.0
5  1006-2   David Strouut      1A  BSIT-1  80.0

In [13]:
student_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       6 non-null      object
 1   name     6 non-null      object
 2   section  6 non-null      object
 3   year     6 non-null      object
 4   gpa      6 non-null      float64
dtypes: float64(1), object(4)
memory usage: 372.0+ bytes

#### deans_list function

In [22]:
def deans_list(gpa):
    return 'Y' if gpa >=90.0 else 'N'

In [23]:
student_df['deans_list'] = student_df['gpa'].apply(deans_list)

In [24]:
student_df

       id            name section    year   gpa deans_list
0  1001-2   Louisa Decker      1A  BSIT-1  91.0          Y
1  1002-2    Sioned Allan      2A  BSIT-2  92.0          Y
2  1003-2  Cayden Collier      3B  BSIT-3  88.0          N
3  1004-2     Jerome Rudd      3D  BSIT-3  83.0          N
4  1005-2   Jibril Morrow      2C  BSIT-2  75.0          N
5  1006-2   David Strouut      1A  BSIT-1  80.0          N

#### Student who are not on deans_list

In [25]:
student_df[student_df['deans_list'] == 'N'][['name', 'year', 'section']]

             name    year section
2  Cayden Collier  BSIT-3      3B
3     Jerome Rudd  BSIT-3      3D
4   Jibril Morrow  BSIT-2      2C
5   David Strouut  BSIT-1      1A

#### First year students who made to the deans_list

In [27]:
student_df[(student_df['year'] == 'BSIT-1') & (student_df['deans_list'] == 'Y')][['name', 'year', 'section']]

            name    year section
0  Louisa Decker  BSIT-1      1A

#### Deans list with a GPA of 90 or higher

In [28]:
student_df[(student_df['gpa'] >= 90.0) & (student_df['deans_list'] == 'Y')][['name', 'year', 'section']]

            name    year section
0  Louisa Decker  BSIT-1      1A
1   Sioned Allan  BSIT-2      2A

#### Average GPA of student per year level

In [29]:
avg_gpa_per_year = student_df.groupby('year')['gpa'].mean().reset_index()

In [30]:
avg_gpa_per_year_col = ['year', 'gpa']

In [34]:
avg_gpa_per_year

     year   gpa
0  BSIT-1  85.5
1  BSIT-2  83.5
2  BSIT-3  85.5

#### Year level with the highest GPA

In [37]:
avg_gpa_per_year.loc[avg_gpa_per_year['gpa'].idxmax(), 'year']

'BSIT-1'

#### Average GPA of BSIT-3 students

In [38]:
avg_gpa_per_year.loc[avg_gpa_per_year['year'] == 'BSIT-3', 'gpa']

2    85.5
Name: gpa, dtype: float64

#### Highest GPA per year level

In [39]:
student_df.loc[student_df.groupby('year')['gpa'].idxmax(), ['year', 'id', 'name', 'section', 'gpa', 'deans_list']]

     year      id            name section   gpa deans_list
0  BSIT-1  1001-2   Louisa Decker      1A  91.0          Y
1  BSIT-2  1002-2    Sioned Allan      2A  92.0          Y
2  BSIT-3  1003-2  Cayden Collier      3B  88.0          N

In [40]:
student_df.groupby('year')['gpa'].describe()

        count  mean        std   min    25%   50%    75%   max
year
BSIT-1    2.0  85.5   7.778175  80.0  82.75  85.5  88.25  91.0
BSIT-2    2.0  83.5  12.020815  75.0  79.25  83.5  87.75  92.0
BSIT-3    2.0  85.5   3.535534  83.0  84.25  85.5  86.75  88.0